nomalab/stainless-ffmpeg

Cargo.toml
src/probe/crop_detect.rs
src/probe/simple.rs
src/stream.rs
tests/probe.json

Probe frames count

---

.travis.yml
Cargo.toml
src/audio_encoder.rs
src/order/decoder_format.rs
src/order/encoder_format.rs
src/order/mod.rs
src/order/parameters.rs
src/probe/black_detect.rs
src/probe/crop_detect.rs
src/probe/deep.rs
src/probe/silence_detect.rs

add bitrate in deep probe and update parameters for silence detection

---

src/format_context.rs
src/stream.rs
tests/probe.json

video bitrate undifined

---

examples/deep_probe.rs
src/probe/black_and_silence.rs
src/probe/deep.rs
src/probe/mod.rs

black and silence detection

---

Cargo.toml
src/probe/silence_detect.rs

correct bug of silences ending a stream and not respecting order

---

Cargo.toml
src/filter.rs
src/filter_graph.rs
src/order/filter_input.rs
src/order/filter_output.rs
src/order/frame.rs
src/order/input.rs
src/order/input_kind.rs
src/order/output.rs
src/order/output_kind.rs
src/order/stream.rs
src/probe/deep.rs
src/probe/silence_detect.rs
src/probe/simple.rs
src/tools/rational.rs

silence bug

---

.github/workflows/main.yml
examples/deep_probe.rs
src/filter.rs
src/format_context.rs
src/order/mod.rs
src/order/output.rs
src/probe/black_detect.rs
src/probe/crop_detect.rs
src/probe/deep.rs
src/probe/mod.rs
src/probe/ocr_detect.rs
src/probe/silence_detect.rs
src/probe/simple.rs

add media offline detection with OCR filter

---

.github/workflows/main.yml

use fixed ffmpeg version for cargo tests

---

Cargo.toml

add exclude files in cargo toml

---

examples/deep_probe.rs
src/probe/deep.rs
src/probe/mod.rs
src/probe/sine_detect.rs
tests/deep_probe.json

add 1000hz detection, update tests

---

src/probe/black_and_silence.rs
src/probe/black_detect.rs
src/probe/crop_detect.rs
src/probe/deep.rs
src/probe/dualmono_detect.rs
src/probe/loudness_detect.rs
src/probe/ocr_detect.rs
src/probe/scene_detect.rs
src/probe/silence_detect.rs
src/probe/sine_detect.rs
tests/deep_probe.json

add Option for detected_analysis

---

src/filter_graph.rs
src/order/decoder_format.rs
src/probe/black_detect.rs
src/probe/crop_detect.rs
src/probe/dualmono_detect.rs
src/probe/mod.rs
src/probe/ocr_detect.rs
src/probe/scene_detect.rs
src/probe/silence_detect.rs
src/probe/sine_detect.rs
src/stream.rs
src/tools/rational.rs
src/video_decoder.rs
tests/deep_probe.json

Fix deep probe framerate result

---

src/probe/dualmono_detect.rs
src/probe/silence_detect.rs
src/probe/sine_detect.rs

Fix deep probe audio

---

examples/deep_probe.rs
src/probe/blackfade_detect.rs
src/probe/deep.rs
src/probe/mod.rs
tests/deep_probe.json

Add fade to black detection

---

src/filter_graph.rs
src/order/decoder_format.rs
src/video_decoder.rs

Fix graph video decoder

---

src/filter_graph.rs
src/order/mod.rs

nomalab/nomalab#4673
nomalab/nomalab#4522

Fix decode and filter for some codecs

---

src/probe/deep.rs
src/probe/scene_detect.rs
tests/deep_probe.json

Update scene detect

---

src/probe/deep.rs
src/probe/scene_detect.rs
tests/deep_probe.json

Deep probe remove false scenes

---

Cargo.toml
src/stream.rs

use regex to get duration from stream metadata

---

src/probe/black_and_silence.rs

fix black and silence for one frame and rename variables

---

src/filter_graph.rs

Fix deepprobe ram leak

---

.github/workflows/main.yml

rust version to 1.85 in yml
